<?php
/**
 * @category    Safe2Pay
 * @package     Safe2Pay_S2P
 * @copyright   Copyright (c) 2014 Safe2Pay. (https://safe2pay.com.br)
 */
if(!defined('S2P_JS_INCLUDED'))
{
	define('S2P_JS_INCLUDED', true);
?>



<script type="text/javascript" src="<?php echo $this->getJsUrl('s2p/prototype/validation.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('s2p/konduto.js') ?>"></script>

<?php
}
?>