<?php
/**
 *
 * @category   Safe2Pay
 * @package    Safe2Pay_S2P
 * @author     Suporte <integracao@safe2pay.com.br>
 */
?>
<?php $_code=$this->getMethodCode() ?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
		<li>
			<label for="<?php echo $_code ?>_symbol" id="label-s2p-criptomoedas-symbol" class="required"><em>*</em><?php echo $this->__('Criptomoeda') ?></label>
			<div class="input-box">

			<select name="payment[s2p_cripto_symbol]" id="<?php echo $_code ?>_symbol" class="required-entry validate-select">
				<option value="BTC">Bitcoin</option>
				<option value="LTC">Litecoin</option>
				<option value="BCH">Bitcoin Cash</option>
			</select>

			</div>
		</li>
</ul>
