<?php
/**
 *
 * @category   Safe2Pay
 * @package    Safe2Pay_S2P
 * @author     Suporte <integracao@safe2pay.com.br>
 */
?>
<?php $_code=$this->getMethodCode() ?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>

			<div class="input-box s2p-criptomoedas-tipo-pessoa">
				<label for="tipo_fisica"><input type="radio" name="tipo_pessoa" id="tipo_fisica" checked> Pessoa física</label>
				<label for="tipo_juridica"><input type="radio" name="tipo_pessoa" id="tipo_juridica"> Pessoa jurídica</label>
			</div>

    </li>
    
    <li>
			<label for="<?php echo $_code ?>_cpf_cnpj" id="label-s2p-criptomoedas-tipo-pessoa" class="required"><em>*</em><?php echo $this->__('CPF do comprador') ?></label>
			<div class="input-box">
				<input type="text" id="<?php echo $_code ?>_cpf_cnpj" name="payment[s2p_boleto_cpf_cnpj]" title="<?php echo $this->__('CPF do comprador') ?>" class="input-text required-entry" autocomplete="off" />
			</div>
		</li>

		<li>
			<label for="<?php echo $_code ?>_symbol" id="label-s2p-criptomoedas-symbol" class="required"><em>*</em><?php echo $this->__('Criptomoeda') ?></label>
			<div class="input-box">

			<select name="payment[s2p_cripto_symbol]" id="<?php echo $_code ?>_symbol" class="required-entry validate-select">
				<option value="BTC">Bitcoin</option>
				<option value="LTC">Litecoin</option>
				<option value="BCH">Bitcoin Cash</option>
			</select>

			</div>
		</li>
</ul>
<script>

	//var nome_empresa_field = document.getElementById('<?php echo $_code ?>_name');
	var cpf_cnpj_field = document.getElementById('<?php echo $_code ?>_cpf_cnpj');
	var formatted = new Formatter(cpf_cnpj_field, { 'pattern': '{{999}}.{{999}}.{{999}}-{{99}}', 'persistent': false });

  $('tipo_fisica').observe('change', function() { 
  	
  	  $('label-s2p-criptomoedas-tipo-pessoa').update("<?php echo $this->__('CPF do comprador') ?>");
  	
  	  cpf_cnpj_field.value = ''; 
  	  
	  formatted.resetPattern('{{999}}.{{999}}.{{999}}-{{99}}');
  });

  $('tipo_juridica').observe('change', function() { 
  	  $('label-s2p-criptomoedas-tipo-pessoa').update("<?php echo $this->__('CNPJ do comprador') ?>");
  	
  	  cpf_cnpj_field.value = ''; 
  	
	  formatted.resetPattern('{{99}}.{{999}}.{{999}}/{{9999}}-{{99}}'); 
	});

  <?php echo 'var cpf_cnpj = "'.$this->getCpfCnpj().'";'; ?>
  if(cpf_cnpj.length == 14)
    $("tipo_fisica").click();
  else if(cpf_cnpj.length == 18)
	$("tipo_juridica").click();
	
  
  $("<?php echo $_code ?>_cpf_cnpj").value = cpf_cnpj;


</script>

<?php if ($_instructions = $this->getInstructions()): ?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <div class="<?php echo $this->getMethodCode() ?>-instructions-content">
            <?php echo nl2br($_instructions) ?>
        </div>
    </li>
</ul>
<?php endif; ?>
