<?php
/**
 *
 * @category   Safe2Pay
 * @package    Safe2Pay_S2P
 * @author     Suporte <integracao@safe2pay.com.br>
 */
?>
<br />
<button style="margin-top: 20px; margin-bottom: 20px;" onclick="window.open('<?php echo $this->getInvoiceUrl() ?>')" title="<?php echo $this->__('Clique aqui para baixar o seu boleto') ?>" class="button" type="button">
    <span><span><?php echo $this->__('Clique aqui para baixar o seu boleto') ?></span></span>
</button>
