<?php
/**
 *
 * @category   Safe2Pay
 * @package    Safe2Pay_S2P
 * @author     Suporte <integracao@safe2pay.com.br>
 */
?>
<br />

<p style="margin-top: 30px;">Deposite <a style="font-weight: 600"><?php echo $this->getCriptoAmount() ?></a> <?php echo $this->getCriptoSymbol() ?> no endereço abaixo:</p>

<center>
    <img src="<?php echo $this->getInvoiceUrl() ?>" style="width: 200px; height: 200px;" />
    <span style="color: gray"><?php echo $this->getCriptoWalletAddress() ?></span>
</center>


<p style="margin-top: 20px;"><span font-weight: 600>Atenção:</span> O tempo de confirmação do pagamento pode variar de acordo com o nível de congestionamento da Blockchain</p>