<?php
/**
 * @category   Safe2Pay
 * @package    Safe2Pay_S2P
 * @author     Suporte <integracao@safe2pay.com.br>
 */
?>
<?php $_items = $this->getItems(); ?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Meus Cartões de Crédito') ?></h1>
    <button type="button" title="<?php echo $this->__('Incluir novo cartão') ?>" class="button" onclick="window.location='<?php echo $this->getAddPaymentMethodUrl() ?>';"><span><span><?php echo $this->__('Incluir novo cartão') ?></span></span></button>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if(count($_items)): ?>
    <table class="data-table" id="my-payment-methods-table">
        <col width="1" />
        <col />
        <col />
        <col width="1" />
        <thead>
            <tr>
                <th></th>
                <th>Número do Cartão</th>
                <!-- <th>Bandeira</th> -->
                <th>Modalidade</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($_items as $row): ?>

            <!-- <?php $maskedCC = $row[2] ?> -->


            <tr>
                <td class="a-center">
                    <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QAAKqNIzIAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAAHdElNRQfjCQwDJAt/vpgyAAAAoklEQVQ4y82TMQ6CYAyFv5/8mwsDTpq4unsnmOAUnkAnDsAhZHRndyWBCUaYGOry66SmHUhshybNa957TQtrhyOmYKdE91ygRgxZw0Kl1lOxRHgm9cCEj+ymhZFWiT6QOMTGYJa0/gAIpRpbIn/owYd6ZAO0jJxCZ+bxy3SDIKTwvsvms+kXw5ktcAey0Bm+iTKet/WBbo6YnL2SoeNq3ao9niymVG1aL5XjAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDE5LTA5LTEyVDAzOjM2OjExKzAwOjAwSbwfUAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAxOS0wOS0xMlQwMzozNjoxMSswMDowMDjhp+wAAAAZdEVYdFNvZnR3YXJlAHd3dy5pbmtzY2FwZS5vcmeb7jwaAAAAAElFTkSuQmCC">
                </td>
                <td>
                    <span class="nobr">
                        <?php echo $row[card_masked_number] ?>
                    </span>
                </td>
                <!-- <td>
                    <span class="nobr">
                        Mastercard
                    </span>
                </td> -->
                <td>
                    <span class="nobr">
                        Crédito
                    </span>
                </td>
                <td class="a-center">
                    <span class="nobr">
                        <a onclick="deletePaymentMethod('<?php echo $this->escapeUrl($this->getDeletePaymentMethodUrl() . '?id=' . $row[customer_card_id] ) ?>')" href="#">Excluir</a>
                    </span>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-payment-methods-table')</script>
<?php else: ?>
    <p><?php echo Mage::helper('s2p')->__('Você ainda não adicionou nenhum cartão.'); ?></p>
<?php endif ?>

<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Voltar') ?></a></p>
</div>
<script type="text/javascript">
    function deletePaymentMethod(url) {
        if(confirm('<?php echo $this->__('Você tem certeza que deseja excluir esse cartão?') ?>')) {
            window.location=url;
        }
        return false;
    }
</script>
