<?php
/**
 *
 * @category   Safe2Pay
 * @package    Safe2Pay_S2P
 * @author     Suporte <integracao@safe2pay.com.br>
 */
?>
<?php if ($_instructions = $this->getInstructions()): ?>
    <ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <li>
            <div class="<?php echo $this->getMethodCode() ?>-instructions-content">
                <?php echo nl2br($_instructions) ?>
            </div>
        </li>
    </ul>
<?php endif; ?>
